name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
  - repo: self

trigger:
  branches:
    include:
      - develop
      - feature/*
      - release/*
      - master
     
      
stages:
  - stage: 'build_dev'
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    displayName: build_dev
    jobs:
      - template: ./azure-pipelines-build.yml
        parameters:
          name: 'build_solution'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (DEV)'
  
  - stage: 'deploy_dev'
    condition: and(succeeded('build_dev'), startsWith(variables['Build.SourceBranch'], 'refs/heads/develop') )
    jobs:
      - template: ./azure-pipelines-deploy.yml
        parameters:
          job_name: deploy_solution
          target_environment: 'AP-Agreements-DEV'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (DEV)'  
  
  - stage: 'build_test'
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    displayName: build_test
    jobs:
      - template: ./azure-pipelines-build.yml
        parameters:
          name: 'build_solution'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (TEST)'
  
  - stage: 'deploy_test'
    condition: and(succeeded('build_test'), startsWith(variables['Build.SourceBranch'], 'refs/heads/develop') )
    jobs:
      - template: ./azure-pipelines-deploy.yml
        parameters:
          job_name: deploy_solution
          target_environment: 'AP-Agreements-TEST'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (TEST)'
          
  - stage: 'build_qa'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
    displayName: build_qa
    jobs:
      - template: ./azure-pipelines-build.yml
        parameters:
          name: 'build_solution'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (QA)'
          
  - stage: 'deploy_qa'
    condition: and(succeeded('build_qa'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release') )
    jobs:
      - template: ./azure-pipelines-deploy.yml
        parameters:
          job_name: deploy_solution
          target_environment: 'AP-Agreements-QA'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (QA)'
          
  - stage: 'build_prod'
    condition:  startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: build_prod
    jobs:
      - template: ./azure-pipelines-build.yml
        parameters:
          name: 'build_solution'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (PROD)'
          
  - stage: 'deploy_prod'
    condition: and(succeeded('build_prod'), startsWith(variables['Build.SourceBranch'], 'refs/heads/master') )
    jobs:
      - template: ./azure-pipelines-deploy.yml
        parameters:
          job_name: deploy_solution
          target_environment: 'AP-Agreements-PROD'
          variable_group_name: 'AP-Agreements - Frontend SharePoint App (PROD)'