parameters:
  # unique name of the job
  job_name: build_package
  # friendly name of the job
  display_name: Building & packaging
  # project name
  project_name: ''
  working_directory: '.'
  variable_group_name: 
jobs:
  - job: ${{ parameters.job_name }}
    displayName: ${{ parameters.display_name }}
    pool:
      vmImage: 'ubuntu-latest'
      demands:
        - npm
        - node.js
        - java
    variables:
      - group: ${{parameters.variable_group_name}}
      - name: npm_config_cache
        value: $(Pipeline.Workspace)/.

    steps:
      - checkout: self

      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x
          checkLatest: true
      - script: |
          echo $(AzureFunctionBaseUrl) # outputs secondValue
        displayName: 'ARM template variables'
      
      - script: |
            npm install
            npm install --global cross-env
            npm run build
        displayName: 'npm install'

      - script: |
            gulp clean
            gulp build
            cross-env AzureFunctionBaseUrl=$(AzureFunctionBaseUrl) aadClientId=$(aadClientId) gulp bundle --ship
            gulp package-solution --ship
            dir
        displayName: 'Build and package solution'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          Contents: |
            sharepoint/**/*.sppkg
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
        inputs:
          Contents: "$(Build.SourcesDirectory)/artifacts/3.19.2003.0/*.*"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
